version: '3.8'

services:
  pymapgis-app:
    build: .
    container_name: pymapgis-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYMAPGIS_ENV=production
      - PYMAPGIS_LOG_LEVEL=INFO
    volumes:
      - pymapgis-data:/app/data
      - pymapgis-logs:/app/logs
    networks:
      - pymapgis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    container_name: pymapgis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pymapgis-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  postgres:
    image: postgis/postgis:15-3.3
    container_name: pymapgis-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pymapgis
      - POSTGRES_USER=pymapgis
      - POSTGRES_PASSWORD=pymapgis_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pymapgis-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pymapgis-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - pymapgis-network
    restart: unless-stopped
    depends_on:
      - pymapgis-app

  prometheus:
    image: prom/prometheus:latest
    container_name: pymapgis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - pymapgis-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: pymapgis-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - pymapgis-network
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  pymapgis-network:
    driver: bridge

volumes:
  pymapgis-data:
  pymapgis-logs:
  redis-data:
  postgres-data:
  prometheus-data:
  grafana-data:
