name: PyMapGIS CI/CD Pipeline
'on':
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: 1.6.1
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
    - name: Configure Poetry
      run: poetry config virtualenvs.create true
    - name: Install dependencies
      run: poetry install --with dev
    - name: Run tests
      run: poetry run pytest && poetry run mypy pymapgis/ && poetry run ruff check
        pymapgis/
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.11'
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
    - name: Configure Poetry
      run: poetry config virtualenvs.create true
    - name: Install dependencies
      run: poetry install --with dev
    - name: Run security scan with bandit
      run: poetry run pip install bandit && poetry run bandit -r pymapgis/ -f json -o security-scan-results.json || true
    - name: Run dependency check
      run: poetry run pip install safety && poetry run safety check || true
  build:
    needs:
    - test
    - security
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          pymapgis/pymapgis-app:latest
          pymapgis/pymapgis-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy-staging:
    needs:
    - build
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to staging
      run: echo 'Deploying to staging environment'
    - name: Run smoke tests
      run: echo 'Running smoke tests'
  deploy-production:
    needs:
    - deploy-staging
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to production
      run: echo 'Deploying to production environment'
    - name: Run health checks
      run: echo 'Running health checks'
